services:

  counterparty-app:
    container_name: counterparty-app
    hostname: 'counterparty-app.${NETWORK_DOMAINNAME}'
    image: riazmey/counterparty:latest
    build:
      context: .
    volumes:
      - /data/counterparty-app/migrations:/app/counterparty/app/migrations/:rw
      - /data/counterparty-app/settings:/app/counterparty/core/settings/:rw
    networks:
      local_network:
        ipv4_address: ${NETWORK_IP_APP}
    ports:
      - '8000:8000'
    command: '/app/counterparty/docker-entrypoint.sh'
    healthcheck:
      test: [ 'CMD', 'curl --fail http://localhost:8000/ || exit 1' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      - counterparty-psql

  counterparty-psql:
    container_name: counterparty-psql
    hostname: 'counterparty-psql.${NETWORK_DOMAINNAME}'
    image: postgres:latest
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS='--data-checksums --locale-provider=icu --icu-locale=ru-RU'
      - LANG=ru_RU.UTF-8
      - LANGUAGE=ru_RU.UTF-8
      - LC_COLLATE=ru_RU.UTF-8
      - LC_CTYPE=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
      - TZ=Europe/Moscow
    networks:
      local_network:
        ipv4_address: ${NETWORK_IP_PSQL}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - source: /data/counterparty-psql
        target: /var/lib/postgresql/data
        read_only: false
        type: bind
        bind:
          create_host_path: true
      - type: tmpfs
        target: /var/run/postgresql
        read_only: false
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DATABASE_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

networks:

  local_network:
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE}
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
